CREATE TABLE IF NOT EXISTS behavior_decision_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  chipId INT NOT NULL,
  phase VARCHAR(32) NOT NULL,
  trustScore INT NULL,
  riskScore INT NULL,
  dailyBudgetUsed INT NOT NULL DEFAULT 0,
  dailyBudgetTotal INT NOT NULL DEFAULT 0,
  sessionId VARCHAR(191) NULL,
  requestedAction VARCHAR(64) NOT NULL,
  decision VARCHAR(32) NOT NULL,
  reason TEXT NOT NULL,
  delayMs INT NULL,
  nextCheckAt TIMESTAMP NULL,
  engineVersion VARCHAR(64) NOT NULL,
  checksJson MEDIUMTEXT NULL,
  contributorsJson MEDIUMTEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_behavior_decision_log_chip_created (chipId, createdAt),
  INDEX idx_behavior_decision_log_created (createdAt)
);

CREATE TABLE IF NOT EXISTS behavior_snapshots (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  chipId INT NOT NULL UNIQUE,
  phase VARCHAR(32) NOT NULL,
  trustScore INT NULL,
  riskScore INT NULL,
  dailyBudgetUsed INT NOT NULL DEFAULT 0,
  dailyBudgetTotal INT NOT NULL DEFAULT 0,
  inboundCount INT NOT NULL DEFAULT 0,
  outboundCount INT NOT NULL DEFAULT 0,
  sessionId VARCHAR(191) NULL,
  lastDecision VARCHAR(32) NULL,
  lastReason TEXT NULL,
  nextCheckAt TIMESTAMP NULL,
  engineVersion VARCHAR(64) NOT NULL,
  snapshotJson MEDIUMTEXT NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_behavior_snapshots_phase (phase),
  INDEX idx_behavior_snapshots_updated (updatedAt)
);
