CREATE TABLE IF NOT EXISTS behavior_action_execution (
  id VARCHAR(64) PRIMARY KEY,
  decisionId VARCHAR(64) NOT NULL,
  userId INT NOT NULL,
  chipId INT NOT NULL,
  requestedAction VARCHAR(64) NOT NULL,
  targetType ENUM('number', 'group', 'list', 'chip') NOT NULL,
  targetValue VARCHAR(255) NOT NULL,
  messageId VARCHAR(128) NULL,
  status ENUM('PENDING', 'SENDING', 'ACKED', 'FAILED', 'RETRYING') NOT NULL DEFAULT 'PENDING',
  budgetState ENUM('NOT_RESERVED', 'RESERVED', 'COMMITTED', 'RELEASED') NOT NULL DEFAULT 'NOT_RESERVED',
  attempt INT NOT NULL DEFAULT 1,
  recoverable INT NOT NULL DEFAULT 1,
  maxAttempts INT NOT NULL DEFAULT 3,
  nextRetryAt TIMESTAMP NULL,
  lastRetryAt TIMESTAMP NULL,
  payload TEXT NULL,
  error TEXT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sentAt TIMESTAMP NULL,
  ackAt TIMESTAMP NULL,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_behavior_action_execution_chip_created (chipId, createdAt),
  INDEX idx_behavior_action_execution_decision (decisionId),
  INDEX idx_behavior_action_execution_status (status)
);
